# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "csvExtractor"
client_id = "e5018ca12803b274fd169bf1c4132069"
application_url = "https://wales-algeria-descending-dam.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://wales-algeria-descending-dam.trycloudflare.com/auth/callback",
  "https://wales-algeria-descending-dam.trycloudflare.com/auth/shopify/callback",
  "https://wales-algeria-descending-dam.trycloudflare.com/api/auth/callback",
  "https://wales-algeria-descending-dam.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wassimsandbox.myshopify.com"
